name: cgk
favicon: null
layout_spectrum: 0.31115
typography_spectrum: 0.39249
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ec4f24'
    - '#ff8f00'
    - '#013c76'
    - '#7294a0'
    - '#96201a'
  brandStrength: 0.625
  lightness: 0.5709694395773113
  saturation: 0.34378036414273083
  rhythmicContrast: 0.7817731730174273
purpose: []
