name: cgk
favicon: null
layout_spectrum: 0.4094446920789778
typography_spectrum: 0.9288094358053058
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.12206938373856246
  lightness: 0.5709694395773113
  saturation: 0.34378036414273083
  rhythmicContrast: 0.7817731730174273
purpose: []
